### PR TITLE
Add Vi Nguyen to Editors

### PR DESCRIPTION
**Pull request by chcunningham**
Resolved at TPAC 2019.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/pull/145.html" title="Last updated on Jan 23, 2020, 5:49 PM UTC (9801ee2)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/media-capabilities/145/4d5d0fb...9801ee2.html" title="Last updated on Jan 23, 2020, 5:49 PM UTC (9801ee2)">Diff</a>

### CODE REVIEW

**Comment by chcunningham** [comment]
@vi-dot-cpp sorry - long overdue. I need your W3c ID and couldn't figure out to look that up? 

Also, technically the tpac notes said we resolved to add Greg, but IIRC that was later changed to be you. Its been a while, so LMK if my memory is right.

**Comment by gregwhitworth** [comment]
@chcunningham Yes, it's Vi - not me

**Comment by mounirlamouri** [comment]
LGTM (note: I've added the w3cid directly in your PR, thanks GitHub for the inline edit feature :))

**Comment by vi-dot-cpp** [comment]
> LGTM (note: I've added the w3cid directly in your PR, thanks GitHub for the inline edit feature :))

For future purposes, may I ask how you found the w3cid? Thank you.

**Comment by mounirlamouri** [comment]
> > LGTM (note: I've added the w3cid directly in your PR, thanks GitHub for the inline edit feature :))
> 
> For future purposes, may I ask how you found the w3cid? Thank you.

The WG member only view of the participants list shows me an "edit status" link that include your "uid". It's possible I only can see that as the chair. You should be able to find this info directly on your w3c member page.

**Pull request merged**
